### PR TITLE
Refactors eom

### PR DESCRIPTION
**Pull request by isaacm**
Attempt at #32

### CODE REVIEW

**Comment by BenjamenMeyer** [comment]
The logging was setup to support each module (auth, governor, etc) having their own log configuration. I think that it will still work the same way but let's verify.

Also, let's make the LOG objects instance specific (self.log) instead of module global (LOG) - cleans up the global namespace.

**Comment by isaacm** [comment]
All tests other than python 2.6 are passing now. I think we can set up py26 tests in such a way that it doesn't fail the whole build.

**Comment by BenjamenMeyer** [comment]
@isaacm given how much of a breaking change this is - everyone using EOM will have to change their deployments, is it possible to write some migration functions so that the old interface could be kept temporarily and marked as deprecated?

The `configure` could probably just save something for the `wrapper` to use, which could then create the appropriate object and return it. Thoughts?

**Comment by isaacm** [comment]
It sounds feasible no objections until I get around to testing that in my dev environment.

**Comment by BenjamenMeyer** [comment]
@isaacm moved this to 0.10 so we can push out a governor timing change in 0.9.

**Comment by TheSriram** [comment]
I like the overall approach, I just have a question, why is the redis_client no longer being wrapped?

**Comment by isaacm** [comment]
Not sure if there was a preference, with this patch all the redis options are read from config file and the redis client is instantiated inside the middleware class. I'd say for simplicity config/instantiation is handled by the middleware now.

Should we allow users to instantiate a redis client and pass it when wrapping?

Looking at the now outdated examples and I see [this](https://github.com/racker/eom/blob/master/eom/utils/redis_pool.py#L30) which seems like a dated version of [this](https://github.com/racker/eom/blob/master/eom/auth.py#L125). All that logic now resides within the middleware class(es).

**Comment by BenjamenMeyer** [comment]
@isaacm can you resolve the conflicts please?

**Pull request closed without merging**
