### PR TITLE
Modify logging messages

### PR DESCRIPTION
**Pull request by isaacm**
Modify log formatting, fix a bug with string formatting.

### CODE REVIEW

**Comment by BenjamenMeyer** [comment]
:+1: Assuming the format works for all supported versions of Python @TheSriram please confirm

Personally my preference is the ```'some string {0}'.format(someValue)``` method. We probably should standardize on one formatting method and update everything to use it correctly. @TheSriram thoughts?

**Comment by TheSriram** [comment]
"my preference is the 'some string {0}'.format(someValue) method" as well. I find it cleaner to read.

**Comment by BenjamenMeyer** [comment]
@TheSriram Per https://github.com/racker/eom/pull/85#issuecomment-138623849 - okay, I'll create an issue to update all the code to using that format.

@isaacm I'll leave it up to you for whether or not you use that format in this PR.

**Comment by isaacm** [comment]
I've updated this PR to include the suggested string format options.

**Comment by BenjamenMeyer** [comment]
:+1:

**Pull request merged**
